apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapplication1-deployment
  labels:
    app: nodejsapplication  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapplication 
  template:
    metadata:
      labels:
        app: nodejsapplication   
    spec:
      containers:
      - name: nodeappserver
        image: good777lord/nodeimage:latest
        ports:
        - containerPort: 3000
