apiVersion: v1
kind: Service
metadata:
  name: nodejsapplication1-service
spec:
  selector:
    app: nodejsapplication  
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31111
